---

- name: Configure HTPasswd Authentication in OpenShift
  hosts: all
  tasks:
    - name: Create HTPasswd file
      command: htpasswd -cB ${PWD}/src/htpasswd <user_name>
      become: yes

    - name: Create HTPasswd Secret in OpenShift
      shell: oc create secret generic htpasswd-secret --from-file=htpasswd=${PWD}/src/htpasswd -n openshift-config

    - name: Apply the HTPasswd CRD
      copy:
        src: ${PWD}/src/htpasswd-crd.yaml
        dest: ${PWD}/src/htpasswd-crd.yaml

    - name: Apply CRD
      shell: oc apply -f ${PWD}/src/htpasswd-crd.yaml
