apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 50-master-kubelet-reserve-resources
spec:
  config:
    ignition:
      version: 3.2.0
    systemd:
      units:
        - name: kubelet.service
          dropins:
            - name: 10-reserve-resources.conf
              contents: |
                [Service]
                Environment="KUBELET_EXTRA_ARGS=--system-reserved=cpu=500m,memory=500Mi --kube-reserved=cpu=500m,memory=500Mi"
