---

- name: Validate Deployments
  hosts: all
  tasks:
    - name: Check RHODS-Operator Pods
      shell: oc get pods -n rhods-operator-namespace
      register: rhods_pods

    - name: Output Pod Status
      debug:
        msg: "{{ rhods_pods.stdout }}"
